### ISSUE TITLE
Looks good. 

### ISSUE THREAD

**Issue by soggybag** [C3NZ/breakout#1]
This looks good. The game is working and you covered a few of the challenges. I see room where you could do more! 

The promise of fried canvas has intrigued me. I'm disappointed that this is promise was never fulfilled.

**Comment by vmarcella** [comment]
Thank you! Deep frying with canvas isn't too easy, as i'd have to manipulate each pixel on the canvas to create the effect of a "deep fried" filter being applied to the screen. Instead, I've added a gradient background along with arcs that cover each wall of the game. The brick grid and screen have also been made bigger for more playtime. Debating on updating the collision detection and fixing the mouse movement, as the mouse doesn't center properly anymore.
