### ISSUE TITLE
Feel this Game could have been it's own class

### ISSUE THREAD

**Issue by soggybag** [C3NZ/breakout#2]
https://github.com/C3NZ/breakout/blob/153855fe9f5716c2088373eb08c8fe88b99f2724/public/js/breakout.js#L5

You have a few things in here that doesn't live up to the classes you've created. Why not make a Paddle Class? A Game class might be a good place to encapsulate all of the methods and properties here. 

That said, you are using modules which encapsulate the variables and functions here.

**Comment by vmarcella** [comment]
Resolved in a much earlier update by using a `Player` class to represent the paddle
